-- Spring Session JDBC schema. Spring Session ships no SQLite variant, so this is
-- the standard schema adapted to SQLite types (TEXT/INTEGER/BLOB). Table and column
-- names must match exactly what Spring Session's fixed SQL expects.

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            TEXT    NOT NULL,
    SESSION_ID            TEXT    NOT NULL,
    CREATION_TIME         INTEGER NOT NULL,
    LAST_ACCESS_TIME      INTEGER NOT NULL,
    MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
    EXPIRY_TIME           INTEGER NOT NULL,
    PRINCIPAL_NAME        TEXT,
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID TEXT NOT NULL,
    ATTRIBUTE_NAME     TEXT NOT NULL,
    ATTRIBUTE_BYTES    BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);
